--ASSOCIATIVE ARRAY
/*
IT IS A SET OF KEY-VALUE PAIRS.
DATA TYPE OF INDEX CAN BE EITHER A STRING TYPE(VARCHAR2,VARCHAR,STRING,LONG) OR PLS_INTEGER.
*/
CLEAR SCREEN
SET SERVEROUT ON
DECLARE
TYPE V_DAY_DET IS TABLE OF VARCHAR2(30) INDEX BY VARCHAR2(30);
V_DAY V_DAY_DET;
BEGIN
V_DAY('FIRST'):='MONDAY';
V_DAY('SECOND'):='TUESDAY';
V_DAY(3):='WEDNESDAY';

DBMS_OUTPUT.PUT_LINE('VALUE IS'||V_DAY('FIRST'));
DBMS_OUTPUT.PUT_LINE('VALUE IS'||V_DAY(3));

END;

