--MULTISET OPERATOR--
/*
SIMILAR TO SET OPERATOR
SET OPERATOR ACT ON RESULTSET OF SQL
WHERE MULTISET ACT ON ELEMENT OF COLLECTION

UNION
UNION ALL
UNION DISTINCT

INTERSECT
INTERSECT ALL
INTERSECT DISTINCT

EXCEPT
EXCEPT ALL
EXCEPT DISTINCT

ALL\DISTINCT(DEFAULT BEHAVIOUR IS ALL)
*/

CLEAR SCREEN
DECLARE
TYPE NUM_TAB_TYPE IS TABLE OF NUMBER;
LV_NUM_LIST1 NUM_TAB_TYPE :=NUM_TAB_TYPE(1,2,3,4,4,5,5);
LV_NUM_LIST2 NUM_TAB_TYPE :=NUM_TAB_TYPE(1,2,3,2,3);
LV_NUM_LIST3 NUM_TAB_TYPE;

BEGIN
    --LV_NUM_LIST3:=LV_NUM_LIST1 MULTISET UNION LV_NUM_LIST2;
    --LV_NUM_LIST3:=LV_NUM_LIST1 MULTISET UNION DISTINCT LV_NUM_LIST2;
    --LV_NUM_LIST3:=LV_NUM_LIST1 MULTISET INTERSECT LV_NUM_LIST2;
    LV_NUM_LIST3:=LV_NUM_LIST1 MULTISET INTERSECT DISTINCT LV_NUM_LIST2;
    FOR I IN 1..LV_NUM_LIST3.COUNT 
    LOOP
    DBMS_OUTPUT.PUT_LINE(LV_NUM_LIST3(I));
    END LOOP;
END;