--RECORD--
/*
1.A RECORD TYPE DEFINED IN A PL/SQL BLOCK IS A LOCAL TYPE.
2.A RECORD DEFINED IN A PACKAGE SPECIFICATION IS A PUBLIC ITEM.
3.YOU CAN NOT CREATE RECORD AT SCHEMA LEVEL
4.TO DEFINE A RECORD TYPE, SPECIFY ITS NAME AND DEFINE ITS FIELD.
5.YOU CAN SPECIFY THE NOT NULL CONSTRAINT FOR A FIELD.
*/

SET SERVEROUTPUT ON
DECLARE
TYPE EMP_DATA_REC IS RECORD(EMP_NAME VARCHAR2(10),EMP_NO NUMBER);
EMP_DATA_DET EMP_DATA_REC;

BEGIN
    EMP_DATA_DET.EMP_NAME :='NITESH';
    EMP_DATA_DET.EMP_NO := 23;

    DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME '||EMP_DATA_DET.EMP_NAME);
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE NO '||EMP_DATA_DET.EMP_NO);

END;
/*
EMPLOYEE NAME NITESH
EMPLOYEE NO 23

PL/SQL procedure successfully completed.
*/


-----------------------------------------------------------------
SET SERVEROUTPUT ON
DECLARE
TYPE EMP_DATA_REC IS RECORD(EMP_NAME VARCHAR2(10),EMP_NO NUMBER);
EMP_DATA_DET EMP_DATA_REC:=EMP_DATA_REC('SAM',23);

BEGIN

    DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME '||EMP_DATA_DET.EMP_NAME);
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE NO '||EMP_DATA_DET.EMP_NO);

END;

/*
EMPLOYEE NAME SAM
EMPLOYEE NO 23

PL/SQL procedure successfully completed.
*/
------------------------------------------------------------------
SET SERVEROUTPUT ON
DECLARE
TYPE EMP_DATA_REC IS RECORD(EMP_NAME VARCHAR2(10),EMP_NO NUMBER);
EMP_DATA_DET EMP_DATA_REC;

BEGIN
    SELECT EMP_NAME,EMP_NO 
    INTO  EMP_DATA_DET 
    FROM EMP WHERE EMP_NO=130;
    
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME '||EMP_DATA_DET.EMP_NAME);
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE NO '||EMP_DATA_DET.EMP_NO);

END;

/*
EMPLOYEE NAME Purnima
EMPLOYEE NO 130

PL/SQL procedure successfully completed.
*/

---------------------------------------------------------------
SET SERVEROUTPUT ON
DECLARE
TYPE EMP_DATA_REC IS RECORD(EMP_NAME VARCHAR2(10) NOT NULL :='NIL' ,EMP_NO NUMBER);
EMP_DATA_DET EMP_DATA_REC;

BEGIN
    EMP_DATA_DET.EMP_NAME :=' ';
    EMP_DATA_DET.EMP_NO := 23;

    DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME '||EMP_DATA_DET.EMP_NAME);
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE NO '||EMP_DATA_DET.EMP_NO);

END;
/*
EMPLOYEE NAME  
EMPLOYEE NO 23

PL/SQL procedure successfully completed.
*/

----------------When the input value is null----------------------------------
SET SERVEROUTPUT ON
DECLARE
TYPE EMP_DATA_REC IS RECORD(EMP_NAME VARCHAR2(10) NOT NULL :='NIL' ,EMP_NO NUMBER);
EMP_DATA_DET EMP_DATA_REC;

BEGIN
    --EMP_DATA_DET.EMP_NAME :=' ';
    EMP_DATA_DET.EMP_NO := 23;

    DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME '||EMP_DATA_DET.EMP_NAME);
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE NO '||EMP_DATA_DET.EMP_NO);

END;

/*
EMPLOYEE NAME NIL
EMPLOYEE NO 23

PL/SQL procedure successfully completed.
*/
