/*
MERGE
MAKE CHANGES IN ANOTHER TABLE USING DIFFERENT SOURCE TABLE
*/

CREATE TABLE EMP_SRC(EMP_NO NUMBER,EMP_NAME VARCHAR2(30),SAL NUMBER);
INSERT INTO EMP_SRC VALUES(1,'RAVI',1000);
INSERT INTO EMP_SRC VALUES(2,'RAGHU',2000);
INSERT INTO EMP_SRC VALUES(3,'PRIYA',3000);
INSERT INTO EMP_SRC VALUES(4,'KAVIN',4000);


CREATE TABLE EMP_TGT(EMP_NO NUMBER,EMP_NAME VARCHAR2(30),SAL NUMBER);
INSERT INTO EMP_TGT VALUES(1,'RAVI',1000);
INSERT INTO EMP_TGT VALUES(2,'RAGHU',2000);
INSERT INTO EMP_TGT VALUES(3,'PRIYA',3000);
INSERT INTO EMP_TGT VALUES(4,'KAVIN',4000);

SELECT * FROM EMP_TGT;
SELECT * FROM EMP_SRC;


MERGE INTO EMP_TGT USING EMP_SRC ON (EMP_TGT.EMP_NO=EMP_SRC.EMP_NO)
WHEN MATCHED THEN
UPDATE SET SAL=EMP_SRC.SAL
WHEN NOT MATCHED THEN
INSERT VALUES(EMP_SRC.EMP_NO,
EMP_SRC.EMP_NAME,
EMP_SRC.SAL);

UPDATE EMP_SRC SET SAL=3500 WHERE EMP_NO=3;
INSERT INTO EMP_SRC VALUES(5,'SUMAN',6000);

-------------------------EXCEPTION OCCURRED DURING MERGE QUERY-----------------------
DROP TABLE EMP_SRC;
CREATE TABLE EMP_SRC(EMP_NO NUMBER,EMP_NAME VARCHAR2(30),SAL NUMBER);
INSERT INTO EMP_SRC VALUES(1,'RAVI',1000);
INSERT INTO EMP_SRC VALUES(2,'RAGHU',2000);
INSERT INTO EMP_SRC VALUES(3,'PRIYA',3000);
INSERT INTO EMP_SRC VALUES(4,'KAVIN',4000);

DROP TABLE EMP_TGT;
CREATE TABLE EMP_TGT(EMP_NO NUMBER,EMP_NAME VARCHAR2(10),SAL NUMBER);
INSERT INTO EMP_TGT VALUES(1,'RAVI',1000);
INSERT INTO EMP_TGT VALUES(2,'RAGHU',2000);
INSERT INTO EMP_TGT VALUES(3,'PRIYA',3000);
INSERT INTO EMP_TGT VALUES(4,'KAVIN',4000);


UPDATE EMP_SRC SET SAL=3500 WHERE EMP_NO=3;
INSERT INTO EMP_SRC VALUES(5,'NITESH SARVESH PANDEY',6000);


BEGIN
DBMS_ERRLOG.CREATE_ERROR_LOG (DML_TABLE_NAME =>'EMP_TGT');
END;

MERGE INTO EMP_TGT USING EMP_SRC ON (EMP_TGT.EMP_NO=EMP_SRC.EMP_NO)
WHEN MATCHED THEN
UPDATE SET SAL=EMP_SRC.SAL
WHEN NOT MATCHED THEN
INSERT VALUES(EMP_SRC.EMP_NO,
EMP_SRC.EMP_NAME,
EMP_SRC.SAL)
LOG ERRORS INTO ERR$_EMP_TGT REJECT LIMIT UNLIMITED;

SELECT * FROM EMP_TGT;
SELECT * FROM EMP_SRC;
SELECT * FROM ERR$_EMP_TGT;
