--PRAGMA AUTONOMOUS COMMAND
/*

IT IS A INDEPENDENT TRANSACTION STARTED BY ANOTHER TRANSACTION,
THE MAIN TRANSACTION.

IT DO SQL OPERATION AND COMMIT OR ROLLBACK ,WITHOUTCOMMITING OR ROLLING BACK THE MAIN TRANSACTION.

IT IS A CHILD TRANSACTION STARTED FROM ANOTHER TRASACTION.
CHILD TRANSACTION IS INDEPENDENT OF MAIN TRANSACTION.
CHILD TRASACTION MUST END WITH COMMIT/ROLLBACK BEFRE RETURNING BACK TO MAIN TRANSACTION.


IN NORAML TRASACTION SCENERIO IS LIKE BELOW:
    1.COMMIT ENTIRE THING
    2.ROLLBACK ENTIRE THING
    3.ROLLBACK TO SPECIFIC SAVEPOINT

IN PRAGMA AUTONOMOUS TRASACTION WE CAN COMMIT SPECIFIC TRASACTION WITHIN MULTIPLE TRANSACTION
WHICH IS NOT POSSIBLE IN NORMAL TRANSACTION.

APPLICATION OF PRAGMA AUTONOMOUS TRANSACTION
1.ERROR LOGGING.
2.COMMIT INSIDE TRIGGER.
3.CALLING A FUNCTION HAVING 'DML STATEMENT' IN SELECT STATEMENT.

*/
DROP TABLE T;

CREATE TABLE T (N NUMBER);

INSERT INTO T VALUES(1);
DECLARE 
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    INSERT INTO T VALUES(2);
    COMMIT;
END;

INSERT INTO T VALUES(3);
ROLLBACK;


SELECT * FROM T;