--%ROWTYPE VS %TYPE
--DATATYPE DEFINITION OF VARIABLE
--ROWTYPE HOLD THE RESULT OF SINGLE ROW ONLY.
--ROWTYPE USED WITH CURSOR ALSO.
--SYNTAX IS TABLE_NAME%ROWTYPE

/*
SET SERVEROUTPUT ON
DECLARE
    LV_NAME VARCHAR2(30);
    LV_SAL NUMBER;
BEGIN
    SELECT EMP_NO ,SAL
    INTO LV_NAME,LV_SAL
    FROM EMP WHERE EMP_NO=100;

DBMS_OUTPUT.PUT_LINE('EMP ID IS '||LV_NAME);
DBMS_OUTPUT.PUT_LINE('EMP SALARY IS '||LV_SAL);
END;


SELECT * FROM EMP;
SET SERVEROUTPUT ON
DECLARE 
    LV_EMP_REC EMP%ROWTYPE;
BEGIN
    SELECT * INTO LV_EMP_REC FROM EMP WHERE
    EMP_NO=100;

DBMS_OUTPUT.PUT_LINE('EMP NAME IS '||LV_EMP_REC.EMP_NAME);
DBMS_OUTPUT.PUT_LINE('EMP_SAL IS '||LV_EMP_REC.SAL);
DBMS_OUTPUT.PUT_LINE('EMP DEPT NUMBER IS '||LV_EMP_REC.DEPT_NO);
END;
*/

/*
SET SERVEROUTPUT ON
DECLARE
 CURSOR C1 IS SELECT EMP_NAME,DEPT_NO FROM EMP;
 LV_EMP_REC C1%ROWTYPE;
BEGIN

OPEN C1;
FETCH C1 INTO LV_EMP_REC;
DBMS_OUTPUT.PUT_LINE('EMP NAME IS '||LV_EMP_REC.EMP_NAME);
DBMS_OUTPUT.PUT_LINE('EMP SALARY IS '||LV_EMP_REC.DEPT_NO);
END;
*/
SELECT * FROM EMP;

--TYPE
--IT IS USED TO DYNAMICALLY ASSIGN THE DATATYPE OF EXISITNG COLUMN TO DECLARE VARIABLE.
--IT IS VERY HELPFUL WHEN WE DONT KNOW THE EXACT DATATYPE OF COLUMN OR IF DATATYPE OF COLUMN CHANGED.
--SYNTAX FOLLW AS TABLE_NAME.COLUMN_NAME%TYPE

SET SERVEROUTPUT ON
DECLARE
LV_NAME EMP.EMP_NAME%TYPE ;
LV_SAL NUMBER;

BEGIN
SELECT EMP_NAME,SAL
    INTO LV_NAME,LV_SAL
    FROM EMP WHERE EMP_NAME='Nitesh';

DBMS_OUTPUT.PUT_LINE('EMP NAME IS '||LV_NAME);
DBMS_OUTPUT.PUT_LINE('EMP SALARY IS '||LV_SAL);
END;

ALTER TABLE EMP MODIFY SAL VARCHAR2(100);
DELETE FROM EMP WHERE SAL IS NOT NULL;
SELECT * FROM EMP;



