/*
1. UNIQUE CONSTRAINT AUTOMATICALLY CREATE A UNIQUE INDEX(BUT NOT ALWAYS)
2. UNIQUE CONSTRAINT IS FOR DATA INTEGRITY ,WHEREAS UNIQUE INDEX IS FOR PERFORMANCE IMPROVEMENT.
3. FOREIGN KEY CAN BE CREATED OVER A UNIQUE CONSTRAINT NOT OVER A UNIQUE INDEX.
*/



CLEAR SCREEN
DROP TABLE T_EMP_DET;

CREATE TABLE T_EMP_DET (EMP_NAME VARCHAR2(50),EMP_NO NUMBER);
ALTER TABLE T_EMP_DET ADD CONSTRAINT EMP_NO_PK_CONSTRAINT PRIMARY KEY(EMP_NO);

--1.DOES CREATING A PRIMARY KEY CONSTRAINT ALWAYS CREATE AN INDEX AUTOMATICALLY.

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='T_EMP_DET';
SELECT * FROM USER_INDEXES WHERE TABLE_NAME='T_EMP_DET';

--IF INDEX ALREADY EXIST AND WE CREATE THE PRIMARY KEY CONTRINT THEN ORACLE DOES NOT CREATE A NEW ENTRY FOR INDEX
DROP TABLE T_EMP_DET;
CREATE TABLE T_EMP_DET (EMP_NAME VARCHAR2(50),EMP_NO NUMBER);
CREATE INDEX T1 ON T_EMP_DET (EMP_NO);--NON UNIQUE 

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='T_EMP_DET';
SELECT * FROM USER_INDEXES WHERE TABLE_NAME='T_EMP_DET';
ALTER TABLE T_EMP_DET ADD CONSTRAINT EMP_NO_PK_CONSTRAINT PRIMARY KEY(EMP_NO);


--2.WILL DROPPING CONSTRAINT WILL DROP UNDERLYING INDEX??(YES BUT NOT ALWAYS TRUE)
--INDEX WILL DROP IF IT IS CREATED AS PART OF AUTOCREATED CONSTRAINT OTHERWISE IT WILL BE NOT DROP WHEN DROPING CONSTAINT.

DROP TABLE T_EMP_DET;

CREATE TABLE T_EMP_DET (EMP_NAME VARCHAR2(50),EMP_NO NUMBER);
ALTER TABLE T_EMP_DET ADD CONSTRAINT EMP_NO_PK_CONSTRAINT PRIMARY KEY(EMP_NO);

CREATE INDEX T1 ON T_EMP_DET (EMP_NO);--NON UNIQUE 

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='T_EMP_DET';
SELECT * FROM USER_INDEXES WHERE TABLE_NAME='T_EMP_DET';

ALTER TABLE T_EMP_DET DROP CONSTRAINT EMP_NO_PK_CONSTRAINT;


--3.WILL DROPPING 'TABLE' WILL DROP UNDERLYING INDEX.(YES)
CLEAR SCREEN
DROP TABLE T_EMP_DET;
CREATE TABLE T_EMP_DET (EMP_NAME VARCHAR2(50),EMP_NO NUMBER);
ALTER TABLE T_EMP_DET ADD CONSTRAINT EMP_NO_PK_CONSTRAINT PRIMARY KEY(EMP_NO);

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='T_EMP_DET';
SELECT * FROM USER_INDEXES WHERE TABLE_NAME='T_EMP_DET';

--4. CAN A PRIMARY KEY CREATE NONUNIQUE INDEX??(YES IN SOME SCENERIO)

-----------------------------
--5.INSERT ONLY UNIQUE ROW FROM SOURCE TO TARGET TABLE USING IGNORE_ROW_ON_DUPKEY_INDEX(T_EMP_DET(EMP_NO))(USING INSERT HINT)
CLEAR SCREEN
DROP TABLE T_EMP_DET;
CREATE TABLE T_EMP_DET (EMP_NAME VARCHAR2(50),EMP_NO NUMBER);
ALTER TABLE T_EMP_DET ADD CONSTRAINT EMP_NO_PK_CONSTRAINT PRIMARY KEY(EMP_NO);


INSERT INTO T_EMP_DET VALUES('NITESH',1);
INSERT INTO T_EMP_DET VALUES('SARVESH',2);
INSERT INTO T_EMP_DET VALUES('PANDEY',3);
INSERT INTO T_EMP_DET VALUES('SAM',4);

DROP TABLE T_EMP_DET_SOURCE;
CREATE TABLE T_EMP_DET_SOURCE (EMP_NAME VARCHAR2(50),EMP_NO NUMBER);
INSERT INTO T_EMP_DET_SOURCE VALUES('NITESH',1);
INSERT INTO T_EMP_DET_SOURCE VALUES('SARVESH',2);
INSERT INTO T_EMP_DET_SOURCE VALUES('NITSAM',5);
INSERT INTO T_EMP_DET_SOURCE VALUES('SAMNIT',6);

SELECT * FROM T_EMP_DET_SOURCE;
SELECT * FROM T_EMP_DET;
ALTER TABLE T_EMP_DET_SOURCE ADD CONSTRAINT EMP_NO_PK_CONSTRAINT1 PRIMARY KEY(EMP_NO);
INSERT INTO T_EMP_DET SELECT * FROM T_EMP_DET_SOURCE;--ERROR OCCURED DUE TO UNIQUE KEY CONSTRAINT ON T_EMP_DET TABLE

CLEAR SCREEN;
INSERT /*+ IGNORE_ROW_ON_DUPKEY_INDEX(T_EMP_DET(EMP_NO))*/
INTO T_EMP_DET SELECT * FROM T_EMP_DET_SOURCE ;


--SCENERIO 2--IF TABLE DOES NOT HAVE PRIMARY CONSTRAINT THEN HOW TO ACHIEVE THE ABOVE SITUATION.
MERGE INTO T_EMP_DET
USING T_EMP_DET_SOURCE ON (T_EMP_DET_SOURCE.EMP_NO=T_EMP_DET.EMP_NO)
WHEN NOT MATCHED THEN
INSERT(
EMP_NAME,EMP_NO)
VALUES
(T_EMP_DET_SOURCE.EMP_NAME,
T_EMP_DET_SOURCE.EMP_NO);

SELECT * FROM T_EMP_DET;


--METHOD-2
INSERT INTO T_EMP_DET
SELECT * FROM T_EMP_DET_SOURCE
MINUS
SELECT * FROM T_EMP_DET;

--METHOD-3
INSERT INTO T_EMP_DET
SELECT * FROM T_EMP_DET_SOURCE
WHERE EMP_NO NOT IN (SELECT EMP_NO FROM T_EMP_DET);
