/*
TABLE FUNCTION

TABLE FUNCTION IS A USER DEFINED PL/SQL FUNCTION THAT RETURNS A COLLECTION OF ROW.
--FUNCTION THAT RETURN COLLECTION CAN BE USED IN SQL QUERIES THAT BEHAVES LIKE RELATIONAL TABLE.
--TABLE FUNCTION NEEDS TO BE FULLY POPULATED BY THE FUNCTION BEFORE RETURNED AS OUTPUT.
--THEY CAN BE QUERIED INSQL USING TABLE OPERATOR.

DRAWBACK
--TABLE FUNCTION FULLY POPULATED BY THE FUCTION BEFORE RETURNED AS OUTPUT.
*/
--SELECT * FROM EMP;
--SELECT * FROM V$VERSION;

CREATE OR REPLACE TYPE
T_NUM_LIST IS TABLE OF NUMBER;

SELECT * FROM TABLE(T_NUM_LIST(1,2,3,4,5));
SELECT * FROM TABLE(T_NUM_LIST(1,2,3,4));

SELECT * FROM (T_NUM_LIST(1,2,3,4));

CREATE OR REPLACE TYPE T_EMP_LIST IS
TABLE OF VARCHAR2(100);

CREATE OR REPLACE FUNCTION FN_GET_EMP_NAME_LIST RETURN T_EMP_LIST
AS
LV_ENAME_LIST T_EMP_LIST:=T_EMP_LIST();

BEGIN
FOR I IN (SELECT EMP_NAME FROM EMP)
LOOP
LV_ENAME_LIST.EXTEND;
LV_ENAME_LIST(LV_ENAME_LIST.LAST):=I.EMP_NAME;
END LOOP;
RETURN LV_ENAME_LIST;
END;

SELECT * FROM TABLE(FN_GET_EMP_NAME_LIST());
SELECT * FROM (FN_GET_EMP_NAME_LIST());


SELECT * FROM (FN_GET_EMP_NAME_LIST()) WHERE ROWNUM<=3;--GETTING ERROR IN TABLE FUNCTION






