--MANUALLY ACCESS ELELEMT FROM CURSOR
CLEAR SCREEN
SET SERVEROUTPUT ON

DECLARE
    CURSOR EMP_LIST IS SELECT EMP_NAME FROM EMP;
    LV_EMP_NAME VARCHAR2(20);
BEGIN

    OPEN EMP_LIST;
        FETCH EMP_LIST INTO LV_EMP_NAME;
        DBMS_OUTPUT.PUT_LINE(LV_EMP_NAME);
        FETCH EMP_LIST INTO LV_EMP_NAME;
        DBMS_OUTPUT.PUT_LINE(LV_EMP_NAME);
    CLOSE EMP_LIST ;
END;


--DYNAMICALLY ACCESS ELELEMT FROM CURSOR
CLEAR SCREEN
SET SERVEROUTPUT ON

DECLARE
    CURSOR EMP_LIST IS SELECT EMP_NAME FROM EMP;
    LV_EMP_NAME VARCHAR2(20);
BEGIN

    OPEN EMP_LIST;
    LOOP
    FETCH EMP_LIST INTO LV_EMP_NAME;
        EXIT WHEN EMP_LIST%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(LV_EMP_NAME);
    END LOOP;
    CLOSE EMP_LIST ;
END;