/*
select * from emp;
SELECT * FROM T_DEPT_DET;
CREATE TABLE T_DEPT_DET(DEP_NO NUMBER ,DEPT_NAME VARCHAR2(30));
INSERT INTO T_DEPT_DET VALUES(10,'COMPUTER ENGG');
INSERT INTO T_DEPT_DET VALUES(20,'IT ENGG');
INSERT INTO T_DEPT_DET VALUES(30,'MECH ENGG');

CREATE OR REPLACE VIEW EMP_VIEW_DEMO AS 
SELECT T1.EMP_NAME,T1.EMP_NO,T2.DEPT_NAME 
FROM T_DEPT_DET T2,EMP T1
WHERE T1.DEPT_NO=T2.DEP_NO;

INSERT INTO T_DEPT_DET VALUES(40,'EXTC ENGG');
INSERT INTO EMP VALUES('NITSAM',134,45678,40);

SELECT * FROM EMP_VIEW_DEMO;

INSERT INTO EMP_VIEW_DEMO VALUES('PAPA',123,'EXTC ENGG');
*/

CREATE OR REPLACE TRIGGER TR_INS_TRIGGER_EMP_VIEW
INSTEAD OF INSERT ON EMP_VIEW_DEMO
DECLARE
LV_CHECK_EXIST NUMBER;

BEGIN
    SELECT COUNT(*) INTO LV_CHECK_EXIST FROM T_DEPT_DET
    WHERE DEP_NO=:NEW.DEP_NO;
    
    IF LV_CHECK_EXIST=0 THEN
    INSERT INTO T_DEPT_DET(DEP_NO,DEPT_NAME) VALUES(:NEW.DEP_NO,:NEW.DEPT_NAME);
    END IF;
    
    SELECT COUNT(*) INTO LV_CHECK_EXIST FROM EMP
    WHERE EMP_NO=:NEW.EMP_NO;
    
    IF LV_CHECK_EXIST=0 THEN
    INSERT INTO EMP(EMP_NAME,EMP_NO,SAL,DEPT_NO) VALUES(:NEW.EMP_NAME,:NEW.EMP_NO,:NEW.SAL,:NEW.DEPT_NO);
    END IF;
    

END TR_INS_TRIGGER_EMP_VIEW;
/

INSERT INTO EMP_VIEW_DEMO(EMP_NAME,EMP_NO,DEPT_NAME) VALUES('Tara2',1310,'IT ENGG');
SELECT * FROM EMP; 

SELECT * FROM EMP_VIEW_DEMO;
SELECT * FROM T_DEPT_DET;