/*
TRIGGER

TRIGGER
--A TRIGGER IS A PL/SQL BLOCK STRUCTURE WHICH IS AUTOMATICALLY FIRED WHEN AN EVEN OCCURS IN THE DATABASE.
--THE EVENT CAN BE DDL,DML OR SYSTEM EVENTS
--A TRIGGER CODE IS AUTOMATICALLY WHEN AN ASSOCIATDEVENT HAPPEN IN DATABASE

TYPE OF TRIGGER
--DML TRIGGER-INSERT UPDATE AND DELETE
--DDL TRIGGER-ALTER DROP TRUNCATE REVOKE RENAME AUDIT
--SYSTEM TRIGGER-LOGON LOGOFF STARTUP SHUTDOWN
--INSTEAD OF TRIGGER-TRIGGER ON VIEW
--COMPOUND TRIGGER-COMBINE DML TRIGGER IN SINGLE BLOCK

1.DML TRIGGER
2.DDL TRIGGER
3.SYSTEM TRIGGER
4.INSTEAD OF TRIGGER
5.COMPOUND TRIGGER

1.DML TRIGGER
ROW LEVEL TRIGGER
INSERT
    BEFORE 
    AFTER
UPDATE
    BEFORE 
    AFTER
DELETE
    BEFORE 
    AFTER


STATEMENT LEVEL TRIGGER
INSERT
    BEFORE 
    AFTER
UPDATE 
    BEFORE 
    AFTER
DELETE
    BEFORE 
    AFTER


PURPOSE OF TRIGGER
--AUDITING
--ENFORCING COMPLEX REFERENCTIAL INTEGRITY
--LOGGING
--ENFORCING SECURITY FOR TRANSACTION
--DATA REPLICATING TO MULTIPLE TABLES
--PREVENT INVALID DATA OR TRANSACTION
--SYSTEM TRIGGERS TO DO SOME INITIAL CLEAN UP ACTIVITY




*/





SELECT * FROM T_STUD;
CREATE SEQUENCE LOG_SEQ;

---BEFORE INSERT STATEMENT LEVEL TRIGGER---
CREATE OR REPLACE TRIGGER ST_BF_INS
BEFORE INSERT ON T_STUD
BEGIN
DBMS_OUTPUT.PUT_LINE('STATEMENT BEFORE INSERT TRIGGER'||LOG_SEQ.NEXTVAL);
END;

---AFTER INSERT STATEMENT LEVEL TRIGGER---
CREATE OR REPLACE TRIGGER ST_AFT_INS
AFTER INSERT ON T_STUD
BEGIN
DBMS_OUTPUT.PUT_LINE('STATEMENT AFTER INSERT TRIGGER'||LOG_SEQ.NEXTVAL);
END;

---BEFORE INSERT ROW LEVEL TRIGGER---
CREATE OR REPLACE TRIGGER RW_BF_INS
BEFORE INSERT ON T_STUD FOR EACH ROW
BEGIN
DBMS_OUTPUT.PUT_LINE('ROW LEVEL BEFORE INSERT TRIGGER'||LOG_SEQ.NEXTVAL);
END;


---AFTER INSERT ROW LEVEL TRIGGER---
CREATE OR REPLACE TRIGGER RW_AFT_INS
AFTER INSERT ON T_STUD FOR EACH ROW
BEGIN
DBMS_OUTPUT.PUT_LINE('ROW LEVEL AFTER INSERT TRIGGER'||LOG_SEQ.NEXTVAL);
END;




SELECT * FROM T_STUD;

SET SERVEROUTPUT ON
BEGIN
INSERT INTO T_STUD VALUES('SAM',129,20);
END;


DROP SEQUENCE LOG_SEQ;
CREATE SEQUENCE LOG_SEQ;
---BEFORE UPDATE STATEMENT LEVEL TRIGGER---
CREATE OR REPLACE TRIGGER ST_BF_UPD
BEFORE UPDATE ON T_STUD
BEGIN
DBMS_OUTPUT.PUT_LINE('STATEMENT BEFORE UPDATE TRIGGER: '||LOG_SEQ.NEXTVAL);
END;

---AFTER UPDATE STATEMENT LEVEL TRIGGER---
CREATE OR REPLACE TRIGGER ST_AFT_UPD
AFTER UPDATE ON T_STUD
BEGIN
DBMS_OUTPUT.PUT_LINE('STATEMENT AFTER UPDATE TRIGGER: '||LOG_SEQ.NEXTVAL);
END;

---BEFORE UPDATE ROW LEVEL TRIGGER---
CREATE OR REPLACE TRIGGER RW_BF_UPD
BEFORE UPDATE ON T_STUD FOR EACH ROW
BEGIN
DBMS_OUTPUT.PUT_LINE('ROW LEVEL BEFORE UPDATE TRIGGER: '||LOG_SEQ.NEXTVAL);
END;


---AFTER UPDATE ROW LEVEL TRIGGER---
CREATE OR REPLACE TRIGGER RW_AFT_INS
AFTER UPDATE ON T_STUD FOR EACH ROW
BEGIN
DBMS_OUTPUT.PUT_LINE('ROW LEVEL AFTER UPDATE TRIGGER'||LOG_SEQ.NEXTVAL);
END;


UPDATE T_STUD SET NAME='PANDEY_NEW' WHERE 1=2;



