--DECODE VS CASE

--BOTH WORK AS SAME BUT CASE PROVIDES MORE IMPLEMENTATION THEN DECODE
--CASE IS EXTENSION OD DECODE FUNCTION

CREATE TABLE T_STUDENT_TBL
( S_NO NUMBER,
S_NAME VARCHAR2(100),
S_MARK NUMBER,
S_RESULT VARCHAR2(1)
);

INSERT INTO T_STUDENT_TBL VALUES(1,'NITESH',85,'P');
INSERT INTO T_STUDENT_TBL VALUES(2,'SARVESH',65,'P');
INSERT INTO T_STUDENT_TBL VALUES(3,'PURNIMA',45,'P');
INSERT INTO T_STUDENT_TBL VALUES(4,'NITSAM',95,'P');
INSERT INTO T_STUDENT_TBL VALUES(5,'SOUMYA',25,'F');
INSERT INTO T_STUDENT_TBL VALUES(6,'ANSH',75,'P');
INSERT INTO T_STUDENT_TBL VALUES(7,'SAM',85,NULL);
INSERT INTO T_STUDENT_TBL VALUES(8,'NIT',30,'F');

SELECT * FROM T_STUDENT_TBL;
--TRUNCATE TABLE T_STUDENT_TBL;

--DECODE EXAMPLE
--FUNCTION PROVIDED BY ORACLE
--ONLY EQUALITY ASSERTION
SELECT S_NAME,S_MARK,S_RESULT,
DECODE(S_RESULT,'P','PASS','F','FAIL','NOT AVAILABLE') AS RESULT FROM T_STUDENT_TBL;


SELECT S_NAME,S_MARK,S_RESULT,
CASE S_RESULT
    WHEN 'P' THEN 'PASS'
    WHEN 'F' THEN 'FAIL'
    ELSE 'RESULT NOT AVAILABLE'
END AS RESULT
FROM T_STUDENT_TBL;


SELECT S_NAME,S_MARK,S_RESULT,
CASE 
WHEN S_RESULT='P' THEN 'PASS'
WHEN S_RESULT='F' THEN 'FAIL'
ELSE 'RESULT NOT AVAILABLE'
END AS RESULT
FROM T_STUDENT_TBL;
