/*
create table T_DISTINCT_DEMO (emp_name varchar2(30));

insert into T_DISTINCT_DEMO values('Nitesh');
insert into T_DISTINCT_DEMO values('Sarvesh');
insert into T_DISTINCT_DEMO values('Sam');
insert into T_DISTINCT_DEMO values('Purnima');
insert into T_DISTINCT_DEMO values('Nitesh');
insert into T_DISTINCT_DEMO values('Sarvesh');
insert into T_DISTINCT_DEMO values('Sam');
insert into T_DISTINCT_DEMO values('Purnima');


select * from T_DISTINCT_DEMO;
*/



SELECT DISTINCT EMP_NAME FROM T_DISTINCT_DEMO;
SELECT DISTINCT(EMP_NAME) FROM T_DISTINCT_DEMO;

SELECT EMP_NAME FROM T_DISTINCT_DEMO T1 INTERSECT 
SELECT EMP_NAME FROM t_distinct_demo T2;

SELECT EMP_NAME FROM T_DISTINCT_DEMO T1 UNION 
SELECT EMP_NAME FROM T_DISTINCT_DEMO T2;

SELECT UNIQUE EMP_NAME FROM T_DISTINCT_DEMO;

SELECT EMP_NAME FROM T_DISTINCT_DEMO 
GROUP BY EMP_NAME 
ORDER BY EMP_NAME;

SELECT EMP_NAME FROM T_DISTINCT_DEMO
UNION
SELECT NULL FROM DUAL WHERE 1=2;

SELECT EMP_NAME FROM T_DISTINCT_DEMO
MINUS
SELECT NULL FROM DUAL;




