--DUAL TABLE IS DUMMY TABLE
--IT IS IN THE SCHEMA OF THE USER SYS BUT ACCESSIBLE BY THE NAME DUAL TO ALL USERS.
--IT HAS ONLY ONE COLUMN AND DATATYPE IS VARCHAR2.
--IT CONTAIN ONE ROW WITH THE VALUE OF X
--USED TO COMPUTE THE FUNCTION

SELECT COUNT(1) FROM DUAL;--1
SELECT * FROM DUAL;--X
DESC DUAL;--DUMMY       VARCHAR2(1) 

SELECT 1+2 FROM DUAL;--3
SELECT SUBSTR('WELCOME',1,2) FROM DUAL;--WE

SELECT ROWNUM ||' * 5 = '||ROWNUM*5  FROM DUAL CONNECT BY LEVEL<=10;

SELECT
    ROWNUM,
    substr(
        'WELCOME', 1, ROWNUM
    ),
    substr(
        'WELCOME', ROWNUM
    )
FROM
    dual
CONNECT BY
    level <= length(
        'WELCOME'
    );