---NVL,NVL2,NULLIF,COALESCE

--NVL Handle Default value for null
--IT TAKES 2 ARGUMENTS
--RETURN 2 ARGUMENT IF FIRST IS NULL ELSE RETURN THE SAME VALUE

select NVL('A',0) from dual;
select NVL(NULL,'B') from dual;
select NVL(NULL,NULL) from dual;

--NVL2 TAKES 3 ARGUMENTS
--IT RETURN 2 ARGUMENT IF 1 ARGUMENT IS NOT NULL ELSE RETURN 3 ARGUMENT
select NVL2('A','B','C') from dual; --B
SELECT NVL2(NULL,'B','C') FROM DUAL;--C
SELECT NVL2('A',NULL,'C') FROM DUAL;--NULL
SELECT NVL2('A','B',NULL) FROM DUAL;--B
SELECT NVL2(NULL,NULL,NULL) FROM DUAL;--NULL

--NULLIF WORKS AS COMPARATOR OF STRING 
--IT TAKES 2 ARGUMENT 
--RETURN NULL IF BOTH ARE SAME ELSE RETURN 1 ARGUMENT
SELECT NULLIF('A','B') FROM DUAL;--A
SELECT NULLIF('A','A') FROM DUAL;--NULL
SELECT NULLIF(NULL,'B') FROM DUAL;--ERROR OCCURRED AS INCOSISTENT DATATYPES
SELECT NULLIF('A',NULL) FROM DUAL;--A

--COALESCE TAKE AS MANY AS ARGUMENTS
--RETURN NEXT NON NULL VALUE FROM GIVEN ARGUMENTS

SELECT COALESCE('A','B','C','D') FROM DUAL;--A
SELECT COALESCE(NULL,'B','C','D') FROM DUAL;--B
SELECT COALESCE(NULL,NULL,'C','D') FROM DUAL;--C
SELECT COALESCE(NULL,NULL,NULL,'D') FROM DUAL;--D
SELECT COALESCE(NULL,NULL,NULL,NULL) FROM DUAL;--NULL

