TRIGGER
--A TRIGGER IS A PL/SQL BLOCK STRUCTURE WHICH IS AUTOMATICALLY FIRED WHEN AN EVEN OCCURS IN THE DATABASE.
--THE EVENT CAN BE DDL,DML OR SYSTEM EVENTS
--A TRIGGER CODE IS AUTOMATICALLY WHEN AN ASSOCIATDEVENT HAPPEN IN DATABASE

TYPE OF TRIGGER
--DML TRIGGER-INSERT UPDATE AND DELETE
--DDL TRIGGER-ALTER DROP TRUNCATE REVOKE RENAME AUDIT
--SYSTEM TRIGGER-LOGON LOGOFF STARTUP SHUTDOWN
--INSTEAD OF TRIGGER-TRIGGER ON VIEW
--COMPOUND TRIGGER-COMBINE DML TRIGGER IN SINGLE BLOCK

PURPOSE OF TRIGGER
--AUDITING
--ENFORCING COMPLEX REFERENCTIAL INTEGRITY
--LOGGING
--ENFORCING SECURITY FOR TRANSACTION
--DATA REPLICATING TO MULTIPLE TABLES
--PREVENT INVALID DATA OR TRANSACTION
--SYSTEM TRIGGERS TO DO SOME INITIAL CLEAN UP ACTIVITY

