select * from emp order by sal desc;

SELECT 
RANK(2300) WITHIN GROUP(ORDER BY SAL DESC),
DENSE_RANK(2300) WITHIN GROUP(ORDER BY SAL DESC)
FROM EMP;

--DELETE FROM EMP WHERE EMP_NO=999999999999999999999999999999999;

SELECT EMP_NAME,SAL,dept_no,
RANK() OVER(ORDER BY SAL DESC),
DENSE_RANK() OVER(ORDER BY SAL DESC)
FROM EMP;

SELECT EMP_NAME,SAL,dept_no,
RANK() OVER(PARTITION BY DEPT_NO ORDER BY SAL DESC),
DENSE_RANK() OVER(PARTITION BY DEPT_NO ORDER BY SAL DESC)
FROM EMP;