DML VS DDL

DDL
--DDL STANDS FOR DATA DEFINITION LAMGUAGE.
--DDL IS AUTO COMMITTED
--DDL TRIGGER WILL EXECUTED
--DDL STATEMENT WORK ON THE WHOLE OBJECT
--NO WHERE CONDITION CAN BE USED ALONG WITH DDL STATEMENTS.
--DDL STATMENTS ARE USED FOR DEFINING DATABASE STRUCTURE LIKE TABLE,VIEW,USERS ETC.
--CREATE,ALTER,DROP,TRUNCATE


DML
--DML STAND FOR DATA MANIPULATION LANGUAGE
--DML STATEMENTS ARE USED TO MANAGE THE DATA STORED INSIDE THE DATABASE.
--DML STATEMENTS WORK ON SELECTED DATA OF TABLE.
--WHERE CONDITION CAN BE USED TO FILTER AND WORK ON SELECTED DATASET.
--ALL CHANGES DONE BY DML NEED TO BE EXPLICITLY COMMIT OR ROLLBACK TO MAKE CHANGES PERMANENTS OR REVERT BACK 
--DML TRIGGERS WILL GET INVOKED.
--INSERT,UPDATE,DELETE,MERGE 





