/*
FORCE VIEW*/

SELECT * FROM T_EMP_DET;
DROP VIEW VIEW_EMP_DET;

CREATE OR REPLACE VIEW VIEW_EMP_DET AS
SELECT * FROM T_EMP_DET_NEW; ---ERROR OCCURED BECAUSE TABLE NOT PRESENT

CREATE OR REPLACE FORCE VIEW VIEW_EMP_DET AS
SELECT * FROM T_EMP_DET_NEW; ---CREATE VIEW WITH COMPILATION ERRORS(BUT VIEW IS INVALID IN STATUS)

SELECT * FROM USER_VIEWS WHERE VIEW_NAME='VIEW_EMP_DET';
SELECT * FROM USER_OBJECTS WHERE OBJECT_NAME='VIEW_EMP_DET';

SELECT * FROM VIEW_EMP_DET;
CREATE TABLE T_EMP_DET_NEW(EMP_NAME VARCHAR2(20));--ONCE TABLE IS CREATED AND CALL THE VIEW THEN STATUS OF VIEW CHANGE FROM INVALID TO VALID


----WITH READ ONLY-----
CREATE OR REPLACE VIEW VIEW_EMP_DET AS
SELECT * FROM T_EMP_DET_NEW WITH READ ONLY ;

INSERT INTO VIEW_EMP_DET VALUES ('PANDEY');--NOT ALLOW TO INSERT THE VALUE IN VIEW DUE TO WITH READ ONLY CONSTRAINT  CREATED ON VIEW

CREATE OR REPLACE VIEW VIEW_EMP_DET_1 AS
SELECT * FROM T_EMP_DET_NEW ;

INSERT INTO VIEW_EMP_DET_1 VALUES ('SARVESH');

-----WITH CHECK OPTION------
--RESTRICT VIEW TO PERFORM DML OPERATION BASED ON THE WHERE CONDITION
--ALLOW CHANGE VALUE FOR SPECIFIC DEPTARTMENT ONLY
SELECT * FROM EMP;
CREATE OR REPLACE VIEW DEPT_10_VIEW AS
SELECT * FROM EMP WHERE DEPT_NO=10
WITH CHECK OPTION;  

SELECT * FROM DEPT_10_VIEW;
UPDATE EMP SET DEPT_NO=20 WHERE EMP_NAME='Sam';

UPDATE DEPT_10_VIEW SET DEPT_NO=30 WHERE EMP_NAME='Sarvesh';
INSERT INTO DEPT_10_VIEW VALUES('MAM',1234,23333,13);
