CREATE TABLE T_STUD (NAME VARCHAR2(10), ID NUMBER,DEPT_NO NUMBER);

INSERT INTO T_STUD VALUES('NITESH',123,30);
INSERT INTO T_STUD VALUES('SARVESH',124,20);
INSERT INTO T_STUD VALUES('PANDEY',125,10);
INSERT INTO T_STUD VALUES('SAM',126,10);
INSERT INTO T_STUD VALUES('TIWARI',127,10);
INSERT INTO T_STUD VALUES('PURNIMA',128,10);
INSERT INTO T_STUD VALUES('TARA',129,10);
INSERT INTO T_STUD VALUES('NIT',130,10);
INSERT INTO T_STUD VALUES('NITSAM',131,10);

SELECT * FROM T_STUD;

--VIEW
--VIEW IS JUST A NAMED QUERY.IT DOES NOT STORE ANYTHING.
--WHEN THERE IS A QUERY ON VIEW,IT RUN THE QUERY OF THE VIEW DEFINITION.
--ONLINE DATA FROM UNDERLYING BASE TABLES.
--NO NEED TO REFRESH.

CREATE OR REPLACE VIEW T_STUD_VIEW AS
SELECT NAME ,DEPT_NO FROM T_STUD;

SELECT * FROM T_STUD_VIEW;

/*
--MATERIALIZED VIEW
--STORES DATA PHYSICALLY AND GET UPDATED PERIODICALLY,WHILE QUERING MV
--OFFLINE DATA FROM UNDERLYINGBASE TABLES
--MATERIALIZED VIEW CAN B SET TO REFRESH MANUALLY,ON A SET SCHEDULE,OR BASE ON
  DATABASE DETECTING A CHANGE IN DATA FROM ONE OF THE UNDERLYING TABLE
*/

CREATE MATERIALIZED VIEW T_STUD_MAT_VIEW AS 
SELECT NAME,ID FROM T_STUD;

SELECT * FROM T_STUD_MAT_VIEW;

--ONCE THE BASE TABLE DELETED THE VIEW DATA ALSO GET DELETED
--BUT SAME IS NOT TRUTH FOR THE MATERIALIZED VIEW.

DELETE FROM T_STUD;
SELECT * FROM T_STUD_VIEW;
SELECT * FROM T_STUD_MAT_VIEW;

--REFRESHING MATERIALIZED VIEW
EXEC DBMS_MVIEW.REFRESH('T_STUD_MAT_VIEW');
