/*VIEW RELATED QUERY*

1. IF WE ADD A NEW COLUMN TO THE BASE TABLE ,WILL THAT COLUMN GET ADDED TO VIEW??
ANS: NO,NOT AUTOMATICALLY WE NEED TO RECOMPILE THE VIEW.IT USES COLUMN NAME IF WE EITHER USE OF * FOR ALL COLUMNS.
CREATE OR REPLACE VIEW NEW_VIEW AS 
  SELECT * FROM EMP;

IT USES COLUMNS NAME AT THE TIME OF STORING THE QUESRY DEFINITION LIKE AS GIVEN BELOW
SELECT EMP_NAME,EMP_ID,SAL,DEPT_ID FROM USER_VIEW TABLE


2. IF WE DROP AN EXISTING COLUMN FROM THE BASE TABLE,WHAT WILL HAPPEN TO VIEW??
ANS: ERROR OCCURRED BECAUSE IT DOES NOT FIND THE COLUMN WITHIN THE TABLE

3. HOW TO CHECK THE LIST OF OBJECT USED IN VIEW??
ANS: USING TABLE USER_VIEW OR USER_OBJECTS

*/
