/*VIEW RELATED QUERY*

1. IF WE ADD A NEW COLUMN TO THE BASE TABLE ,WILL THAT COLUMN GET ADDED TO VIEW??
2. IF WE DROP AN EXISTING COLUMN FROM THE BASE TABLE,WHAT WILL HAPPEN TO VIEW??
3. HOW TO CHECK THE LIST OF OBJECT USED IN VIEW??
*/